#!/usr/bin/php
<?php
// genall - generate all the icons.
// Copyright 2016 Creative Commons Corporation.

/*
  In config.json:

  Suites are l for licenses, p for public domain tools.

  Each license/tool has a list of strings of symbol font characters after it.

  Dimensions are [width, height, font size, inter-icon spacing]

  Colors are [background, foreground]
*/

require (dirname(__FILE__) . '/genicon.php');
require (dirname(__FILE__) . '/foregrounds.php');

////////////////////////////////////////////////////////////////////////////////
// Configuration
////////////////////////////////////////////////////////////////////////////////

$font = './cc-icons.ttf';

$config  = json_decode(file_get_contents(dirname(__FILE__) . '/config.json'),
                       $assoc=TRUE);

$suites = ["l" => ["by" => ["b"],
                   "by-nc" => ["bn", "be", "by"],
                   "by-nd" => ["bd"],
                   "by-sa" => ["ba"],
                   "by-nc-nd" => ["bnd", "bed", "byd"],
                   "by-nc-sa" => ["bna", "bea", "bya"]],
           "p"=> ["cc-zero" => ["0"],
                  "public-domain-mark" => ["p"]]];

$dimensions = [[88, 31, 24, 1, 28],
               [80, 15, 10, 4, 13],
               [76, 22, 19, 1, 21]];

$backgrounds = ["transparent",
                "000000",
             // Bootstrap well grey
                "EEEEEE",
                "FFFFFF"];

$foregrounds = foregrounds();

$basedir = dirname(__FILE__) . '/build';

function iconpath ($suite, $license, $background, $foreground) {
    return implode('/', [$suite, $license, $background, $foreground]);
}

function iconFilename ($dimensions, $module_characters) {
    $filename = $dimensions[0] . 'x' . $dimensions[1];
    if (strpos($module_characters, 'y') !== FALSE) {
        $filename .= '-y';
    } elseif (strpos($module_characters, 'e') !== FALSE) {
        $filename .= '-e';
    }
    return $filename . '.png';
}

function ensurePath ($path) {
    if (! file_exists($path)) {
        $ok = mkdir($path, 0777, TRUE);
        if (! $ok) {
            echo "Error creating dir: " . $path . "\n";
            exit(1);
        }
    }
}

foreach ($suites as $suite => $licenses) {
    foreach ($licenses as $license => $modules_list) {
        foreach ($modules_list as $module_chars) {
            foreach ($dimensions as $size) {
                foreach ($backgrounds as $background) {
                    foreach ($foregrounds as $foreground) {
                        $path = $basedir . '/' . iconPath($suite, $license,
                                                          $background,
                                                          $foreground);
                        ensurePath($path);
                        $img = genicon ($module_chars, $font,
                                        $size[2], $size[4], $size[3],
                                        $size[0], $size[1],
                                        $background, $foreground);
                        $filepath = $path . '/' . iconFilename($size,
                                                               $module_chars);
                        $ok = imagepng($img, $filepath);
                        imagedestroy($img);
                        if ($ok === FALSE) {
                            echo "Error writing file: " . $filepath . "\n";
                            exit(1);
                        }
                        echo $filepath . "\n";
                    }
                }
            }
        }
    }
}

/* Local Variables:  */
/* mode: php         */
/* End:              */
