name: genicons_ci

on:
  push:
    # Only run if,
    paths:
      # Changes in python, yaml(github actions)
      - "**.py"
      - "**.yaml"
  pull_request:
    # Only run if,
    paths:
      # Changes in python, yaml(github actions)
      - "**.py"
      - "**.yaml"

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          # Matches Python3 version on Debian Bookworm
          python-version: 3.11
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Python dependencies
        run: |
          pip install black flake8
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Testing with flake8
        run: |
          flake8 ./scripts/genicons.py
      - name: Testing with black
        run: |
          black --check -l 79 ./scripts/genicons.py

  test:
      runs-on: ubuntu-latest

      steps:
        - name: Install dependencies
          run: |
            sudo apt-get install gir1.2-pango-1.0 python3-gi-cairo
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install CC Fonts
          run: |
            sudo mkdir -p ~/.fonts
            sudo ln -sf ${PWD}/www/cc-icons.ttf ~/.fonts/
        - name: Run genicons.py
          run: python3 scripts/genicons.py

